apiVersion: v1
kind: PersistentVolume
metadata:
  name: searxng-config
  namespace: dungeon
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/scrapheap/projects/dungeon/searxng/searxng/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - colima
