apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-loadbalancer
spec:
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    operator.prometheus.io/name: prometheus-stack-kube-prom-prometheus
    app.kubernetes.io/name: prometheus
  type: LoadBalancer
status:
  loadBalancer: {}
