apiVersion: v1
kind: Service
metadata:
  labels:
    app: homarr
  name: homarr-loadbalancer
spec:
  ports:
  - name: http-web
    port: 7575
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: homarr
    app.kubernetes.io/name: homarr
  type: LoadBalancer
status:
  loadBalancer: {}
