apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config
  namespace: dungeon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Mi
  volumeName: searxng-config
